#pragma once

#define SPLIT_USB_DETECT
#define MASTER_LEFT
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE

#define IDLE_TIMEOUT_SECONDS 5
#define IDLE_TIMEOUT_MS (IDLE_TIMEOUT_SECONDS * 1000)
